### ISSUE TITLE
Problem 4

### ISSUE THREAD

**Issue by berasaikat** [Roudranil/probability-and-statistics-with-r-assignment#6]
Problem 4 is solved by Saikat Bera

**Comment by Roudranil** [comment]
https://bookdown.org/yihui/rmarkdown-cookbook/hide-one.html
Try this book. They have some solutions regarding not showing warnings, text outputs etc.
Hope this helps.

**Comment by berasaikat** [comment]
Ok the issue is resolved. Got hold of Warning = False, results = False functions.

**Comment by berasaikat** [comment]
Another issue in Part C and Part D, optim function is crashing, having Inf, -Inf values.

**Comment by shreyanc07** [comment]
There is zero value in one of the columns. You can try removing that value or not taking log. That'll solve your problem.

**Comment by berasaikat** [comment]
Ok, Thanks. Got it.

**Comment by berasaikat** [comment]
Problem has been solved and uploaded.
