### ISSUE TITLE
Issue regarding predict function

### ISSUE THREAD

**Issue by shreyanc07** [Roudranil/probability-and-statistics-with-r-assignment#9]
How to access new data while using predict function?

**Comment by Roudranil** [comment]
I think you should check out this [youtube video](https://www.youtube.com/watch?v=sPnS1SlpJvE)

**Comment by shreyanc07** [comment]
Will there be any difference if i just formulate the predicted variable using the linear model fit apart from using predict function?

**Comment by berasaikat** [comment]
This blog might help [https://stackoverflow.com/questions/53896414/how-to-get-the-new-column-with-predict-function](url)

**Comment by shreyanc07** [comment]
ok
